# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Package and release
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install
      - name: lint
        run: |
          black . -q --check --diff --fast
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --statistics
          npm run lint
      - name: test
        run: pytest
